### ISSUE TITLE
CSS布局(二): 浮动

### ISSUE THREAD

**Issue by ivanberry** [ivanberry/readyToJob#13]
## 浮动定位

浮动最初是用来使得文字环绕在图片周边的,现在它被拓展了,更多使用于块级得布局,更是运用实现了一些现代得布局框架.浮动元素是一个脱离文档流得类块级元素,它不会影响块级元素,但是会影响包含在块级元素中的行盒.标准规定:

> A float is a box that is shifted to the left or right on the current line. The most interesting characteristic of a float (or "floated" or "floating" box) is that content may flow along its side (or be prohibited from doing so by the 'clear' property). Content flows down the right side of a left-floated box and down the left side of a right-floated box.

浮动特性:
- 脱离文档流,从而不影响文档中块级元素得竖直布局.
- 与包含元素左对齐或右对齐
- 浮动总是自左或自右排列,并以文档中出现得顺序排列先后
- 浮动元素使得行盒变窄,这就是环绕得效果
- 不影响包含元素高度,这就是浮动清除适用的原因
- 浮动可被`clear`清除

浮动对齐包含元素的外边缘,或者前一浮动元素的外边缘.

``` css
.left {
  float: left;
}
.right {
  float: right;
}
```

``` html
<div class="left red">A</div>
<div class="right blue">B</div>
<div class="left red">C</div>
<div class="right blue">D</div>
<div class="left red">E</div>
<div class="right blue">F</div>
```

![float](http://7xq1dj.com1.z0.glb.clouddn.com/float.png)

若行宽度不够,临近浮动元素得元素会向下移动,浮动不影响文档流中块级元素得竖直排列,但是却会影响它包含元素行盒.

``` css
.float {
  float: left;
  height: 500px;
}
.para {
  margin: 0;
}
```

``` html
<div class="para blue">Text inside a block-level box placed on a line box before the float</div>
<div class="para green">Text before the float. <div class="float red">The float</div> Text after the float.</div>
<div class="para orange">Text inside a block-level box placed on a line box after the float</div>
```

![float2](http://7xq1dj.com1.z0.glb.clouddn.com/float2.png)

浮动不会影响文档流中新建立块级格式化环境中得行盒内容,它们会完全出现在浮动得一侧,或者移动至浮动以下.

``` css
.float {
  float: left;
  height: 500px;
}
.para {
  margin: 0;
}
.new-context {
  margin: 0;
  overflow: auto;
}
```

``` html
<div class="para blue">before</div>
<div class="float red">The float</div>
<div class="new-context green">new formatting context<br>foo bar</div>
<div class="para orange">after</div>
```

![float3](http://7xq1dj.com1.z0.glb.clouddn.com/float3.png)
## 浮动清除: `clear`

[clear](https://developer.mozilla.org/en-US/docs/Web/CSS/clear)
- `left`: HTML源文档中出现在左浮动元素之前元素的上内边缘置于浮动元素外边缘之下
- `right`: 同`left`影响右浮动元素之后元素的内边缘置于浮动元素外边缘之下
- `both`: 同上影响浮动元素的前后元素
- `none`: 无

``` css
div {
border: 2px solid black;
}
.orange {
border-color: orange;
}
.red {
border-color: red;
}
.blue {
border-color: blue;
}
.left {
float: left;
width: 35%;
height: 40px;
}
```

``` html
<div class="orange">
  <div class="left blue">A</div>
  <div class="left blue">B</div>
  <div class="left red">C</div>
  <div class="left red">D</div>
</div>
```

![float](http://7xq1dj.com1.z0.glb.clouddn.com/float4.png)
### clearfix

浮动清除作用有二:
- 一为阻止影响浮动后续的行盒内元素
- 二为使得浮动包含元素考虑浮动元素得高度(多列布局中常用)

``` css
.left {
  float: left;
  width: 15%;
  height: 40px;
}
```

``` html
<div class="row clearfix blue">
  <div class="left blue">A</div>
  <div class="left blue">B</div>
</div>
<div class="row clearfix green">
  <div class="left green">C</div>
  <div class="left green">D</div>
</div>
<div class="row clearfix orange">
  <div class="left orange">E</div>
  <div class="left orange">F</div>
</div>
```

![clearfix1](http://7xq1dj.com1.z0.glb.clouddn.com/clearfix.png)

我们要使他们都正处于自已父元素中,方法有三:
- 加一个元素,它有`clear: both`属性
- 给父级元素后加个伪元素,它有`clear: both`属性
- 新建立块级格式化环境(eg: overflow: hidded/auto. float)

[具体例子](http://tabgre.com/content/htmlAndCss/2015/float-clearfix.html)
