### ISSUE TITLE
Box sizing in css

### ISSUE THREAD

**Issue by ivanberry** [ivanberry/readyToJob#15]
# 盒大小

元素盒大小由盒模型决定，但定位方式对它有重大的影响，如果不将盒模型置于特定的格式化上下，独立出来说明盒模型的定义，不但不能很好的掌握它，反倒影响对它的深入学习。

盒模型：

![selection_005](https://cloud.githubusercontent.com/assets/13112910/13194284/b6c3cf3a-d7c6-11e5-93c0-4efd8e00e5d5.png)

![boxdim](https://cloud.githubusercontent.com/assets/13112910/13194296/47de4450-d7c7-11e5-9d73-b20ab2e47dc6.png)

盒模型中都包含有：
- margin
- border
- padding
- the content width / height

![selection_006](https://cloud.githubusercontent.com/assets/13112910/13194977/9fd81704-d7df-11e5-8a11-1cc5b4d8fb1b.png)
## Content

`padding`和`border`俩没有什么特别的，稍微提一点，行内元素的`border`（除去inline-block)只会产生一次的`border-left`和`border-right`，这其实是无可厚非的。

![selection_007](https://cloud.githubusercontent.com/assets/13112910/13194994/515e476e-d7e0-11e5-9473-484f21a4152e.png)

上图中
- 第一段是块级元素，所以`border`是连续的，且只有一条
- 第二段则不同，它是inline(`span`)元素，所以它的`border`表现为如图样式

下面说说两个稍微复杂的事情：
1. 内容(content)的维度计算(weight / height)
2. `margin: auto`的作用

在这里我们仅仅讨论non-replace元素，更多的细节详情可参考[visual formatting model details](https://www.w3.org/TR/CSS2/visudet.html)。

![selection_008](https://cloud.githubusercontent.com/assets/13112910/13195026/411f6bca-d7e1-11e5-80d7-caaf7fd86fdf.png)
### 行内元素的盒模型计算

如图所示，`width`, `height`直接被忽略，行内元素存在与行盒子中，而行盒子的大小可有`font-size`和`line-height`决定，同样地， `margin-top`,`margin-bottom`也会被忽略，而`margin-left`,`margin-right`会使得行内元素在行盒子中产生偏移，默认`auto`为解析为0。
### 基于”内容”的高度

_block_, _float_, _inline-block_的高度为`auto`时表现一致，为“基于内容”，那到底什么是“基于内容”来决定它们的高度大小呢？

规范规定了两种不同的计算方法：
- overflow不是`visible`的_block inline-block block-level_元素
- `overflow: visible`

这两个不同的情形的计算方法，其实我们经常遇到过，为什么会以`overflow: visible`来区分呢？它是块级元素的默认值，对的，浮动元素的父容器高度不会计算它的高度，从而需要浮动清除技术，原来是因为这样子才需要浮动清除哟！而另外一种无需多说，新的格式化上下文建立了。

所以，我们可以得到这样的结论，默认(`auto`)高度是基于内容的，它会为包含所有元素而拓展高度，除非你明确规定了一个高度值。
### 宽度计算
1. 基于约束的宽度计算：块级元素会受盒模型影响
2. 缩小以适应的宽度计算： _float_和_inline-block_的宽度计算，它需要考虑三个方面：
        1. 最佳宽度
        2. 最佳最小宽度
        3. 可用宽度
#### 基于约束

块级元素的约束来自与盒模型的几个参数，简单可列出以下的公式：

> 'margin-left' + 'border-left-width' + 'padding-left' + 'width' + 'padding-right' + 'border-right-width' + 'margin-right' = width of containing block

`border`和`padding`只能设定为特定的值，我们可以简化公式为：

> margin-left + width + margin-right = width of containing block

当所有的值为特定值时，那就直截了当就是那么多，而基于约束的触发有下面几种情况：
- 都是`auto`
- 明确width值，而`margin: auto`
- 二个确定值，一个auto

第一中情况时，`width: auto`，其他二者的auto变为0

``` css
.width-auto {
width: auto;
margin: auto;
background-color: orange;
}
```

``` html
<div class="width-auto">width: auto, margin: auto</div>
```

![selection_009](https://cloud.githubusercontent.com/assets/13112910/13195210/46ac5f7a-d7e7-11e5-866c-47efc4defc72.png)

第二种情况就是我们常用的块级元素的居中：需设定width值

最后一种情况是有两个明确的值，那就按照明确值来定义吧！

``` css
      .orange {
        width: 200px;
        margin-left: 15px;
        margin-right: auto;
        background-color: orange;
      }
      .blue {
        width: 300px;
        margin-right: 15px;
        margin-left: auto;
        background-color: lightblue;
      }
```

``` html
<div class="orange">width: auto, margin: auto</div> 
<div class="blue">width: 100px, margin-right: 15px the other is auto</div>
```

![selection_010](https://cloud.githubusercontent.com/assets/13112910/13195270/2c7a36a2-d7e9-11e5-96ee-750d425e7941.png)
#### 缩小以适应

浮动元素和行内元素的宽度计算相对复杂点，规范的描述是这样的：

> If 'width' is computed as 'auto', the used value is the "shrink-to-fit" width.
> 
> Calculation of the shrink-to-fit width is similar to calculating the width of a table cell using the automatic table layout algorithm. Roughly: calculate the preferred width by formatting the content without breaking lines other than where explicit line breaks occur, and also calculate the preferred minimum width, e.g., by trying all possible line breaks. CSS 2.1 does not define the exact algorithm. Thirdly, find the available width: in this case, this is the width of the containing block minus the used values of 'margin-left', 'border-left-width', 'padding-left', 'padding-right', 'border-right-width', 'margin-right', and the widths of any relevant scroll bars.
> 
> Then the shrink-to-fit width is: min(max(preferred minimum width, available width), preferred width).

说人话就是：**_最佳最小值与可用宽度值取大后和最佳宽度值取最小值**_，这尼玛说的也是方言啊！不过还是可以理解的哈！

例子说话：

``` css
    .blue {
        border: 2px solid blue;
    }
    .big {
        width: 100px;
    }
    .small {
        width: 80px;
    }
    .inline-block {
        display: inline-block;
    }
    .orange {
        background-color: orange;
    }
    .blue {
        background: lightskyblue;
    }
    .green {
        background: lightgreen;
    }
    .pink {
        background-color: pink;
    }

```

``` html
<div class="blue">
<div class="orange inline-block">AAAAAAAA BBBB</div>
</div>

<div class="big blue">
<div class="green inline-block">AAAAAAAA BBBB</div>
</div>

<div class="small blue">
<div class="pink inline-block">AAAAAAAA BBBB</div>
</div>
```

![selection_011](https://cloud.githubusercontent.com/assets/13112910/13195373/7126b954-d7eb-11e5-932a-55ea0df5ac21.png)
### 浮动、行内元素的`margin`

它们的值很简单，设置为`auto`时等效为0,无需多议
### 绝对定位元素大小计算

因为绝对定位的存在，所以需要加入`top`等值：

> 'top' + 'margin-top' + 'border-top-width' + 'padding-top' +'height' + 'padding-bottom' + 'border-bottom-width' +'margin-bottom' + 'bottom'= height of containing block
> 
> 'left' + 'margin-left' + 'border-left-width' + 'padding-left' +'width' + 'padding-right' + 'border-right-width' + 'margin-right' +'right'= width of containing block

同样可简化为：

> 'top' + 'margin-top' + 'height' + 'margin-bottom' + 'bottom'= height of containing block
> 
> 'left' + 'margin-left' + 'width' + 'margin-right' + 'right'= width of containing block

更加简单的说就是：

> the content + offsets from the container box + margins must add up to the container's dimensions

可以细化为3大方面，5小方面：**width + the left & right margins + left & right offsets, or height + the top & bottom margins + top & bottom offsets**

那么问题来了，具体怎么实施呢？这样子实施：
- 都有限定值，那就按部就班
- 只有`margin: auto`，那不好意思，爷，您居中
- 只有`margin-left / margin-right : auto`，那就基于约束去计算另外一个`margin`
- 其他所有情况就是：`margin: auto`==>`margin: 0`
  - 其他都不是`auto`，按部就班
  - 有一个`auto`，基于约束计算另外两个
  - 有俩个个是`auto`，其中一个是 `width / height`，或基于约束或基于缩小以适应来计算 `width / height`。
  - 若三个都是`auto`,此处略去不说，**_[待议](http://book.mixu.net/css/2-box-model.html)**_

从上我们隐约可知，通过`position: absolute`可以[水平竖直居中元素](http://tabgre.com/content/htmlAndCss/2015/centering-elements.html)。但是这种方法也不完美，存在这样的问题：
- 太独立，甚至覆盖文档流其它元素
- 须设置过多值： `width / height left / right / top / bottom

[绝对局中的实例](http://codepen.io/shshaw/full/gEiDt)
# 影响定位的额外属性
- Margin collapsing
- Negative margins
- Overflow
- max-width, max-weight, min-width, min-weight
- Pseudo-elements
- Stacking contexts and rendering order
## Margin collapsing

两盒交战，大者胜
1. 竖直合并：只有vertical margin才有合并现象，水平方向永不合并
2. 块盒合并，仅此一家：什么floats, absolutely, inline-block等都不会有，更别说inline-level元素 
3. 一屋子人才亲：只有同以格式化上下文的块盒才有合并的概念
4. 紧紧才融合：只有被认为毗邻的Margin才会有合并

**Comment by ivanberry** [comment]
在放一个利用绝对局中的实例：

``` html
<div class="blue">
<div class="center"></div>
</div>
```

``` css
    .blue {
        background: lightblue;
        position: relative;
        height: 400px;
    }
    .center {
        width: 200px;
        height: 200px;
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        margin: auto;
        background: orange;
    }
```

![selection_012](https://cloud.githubusercontent.com/assets/13112910/13195606/ce1eb688-d7f1-11e5-845a-5f01f4b5c8eb.png)

这个例子最重要的是看图中tools工具中计算出来的**盒模型**。
